//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSosyal
    {
        public int SosyalID { get; set; }
        public string SoyalName { get; set; }
        public string SoyalLink { get; set; }
        public string Sosyalİcon { get; set; }
        public Nullable<bool> SosyalValue { get; set; }
    }
}
